[2025-06-06 12:01:20] uvicorn.error:318 INFO    - Will watch for changes in these directories: ['D:\\Programming\\url_shorter\\backend\\app']
[2025-06-06 12:01:20] uvicorn.error:524 INFO    - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
[2025-06-06 12:01:20] uvicorn.error:80 INFO    - Started reloader process [14872] using WatchFiles
[2025-06-06 12:01:21] uvicorn.error:83 INFO    - Started server process [22656]
[2025-06-06 12:01:21] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:01:21] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:01:23] root:25 INFO    - GET http://127.0.0.1:8000/docs - 200 - 0.46ms
[2025-06-06 12:01:24] root:25 INFO    - GET http://127.0.0.1:8000/openapi.json - 200 - 1.87ms
[2025-06-06 12:02:55] root:18 ERROR   - POST http://127.0.0.1:8000/shorten - ERROR - 'range' object cannot be interpreted as an integer - 2.71ms
Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 18, in shorten
    code = generate_code()
  File "D:\Programming\url_shorter\backend\app\utils\make_link.py", line 5, in generate_code
    return ''.join(choices(string.ascii_letters + string.digits, k=length))
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\random.py", line 471, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
                                                     ~~~~~~~^^^^^^^^^
TypeError: 'range' object cannot be interpreted as an integer
[2025-06-06 12:02:55] uvicorn.error:414 ERROR   - Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 177, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     ) from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         self.scope, self.receive, self.send
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     )
    |     ^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ~~~~~~~~~~~~~~~~~~^^
    |   File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    |     self.gen.throw(value)
    |     ~~~~~~~~~~~~~~^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    |     raise app_exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    |     await route.handle(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     ...<3 lines>...
    |     )
    |     ^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 18, in shorten
    |     code = generate_code()
    |   File "D:\Programming\url_shorter\backend\app\utils\make_link.py", line 5, in generate_code
    |     return ''.join(choices(string.ascii_letters + string.digits, k=length))
    |                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\random.py", line 471, in choices
    |     return [population[floor(random() * n)] for i in _repeat(None, k)]
    |                                                      ~~~~~~~^^^^^^^^^
    | TypeError: 'range' object cannot be interpreted as an integer
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
                                   ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 18, in shorten
    code = generate_code()
  File "D:\Programming\url_shorter\backend\app\utils\make_link.py", line 5, in generate_code
    return ''.join(choices(string.ascii_letters + string.digits, k=length))
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\random.py", line 471, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
                                                     ~~~~~~~^^^^^^^^^
TypeError: 'range' object cannot be interpreted as an integer
[2025-06-06 12:03:22] uvicorn.error:55 WARNING - WatchFiles detected changes in 'utils\make_link.py'. Reloading...
[2025-06-06 12:03:22] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:03:22] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:03:22] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:03:22] uvicorn.error:93 INFO    - Finished server process [22656]
[2025-06-06 12:03:23] uvicorn.error:83 INFO    - Started server process [27896]
[2025-06-06 12:03:23] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:03:23] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:03:24] root:18 ERROR   - POST http://127.0.0.1:8000/shorten - ERROR - 'range' object cannot be interpreted as an integer - 1.80ms
Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 18, in shorten
    code = generate_code()
  File "D:\Programming\url_shorter\backend\app\utils\make_link.py", line 5, in generate_code
    return ''.join(choices(string.ascii_letters + string.digits, k=length))
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\random.py", line 471, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
                                                     ~~~~~~~^^^^^^^^^
TypeError: 'range' object cannot be interpreted as an integer
[2025-06-06 12:03:24] uvicorn.error:414 ERROR   - Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 177, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     ) from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         self.scope, self.receive, self.send
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     )
    |     ^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ~~~~~~~~~~~~~~~~~~^^
    |   File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    |     self.gen.throw(value)
    |     ~~~~~~~~~~~~~~^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    |     raise app_exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    |     await route.handle(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     ...<3 lines>...
    |     )
    |     ^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 18, in shorten
    |     code = generate_code()
    |   File "D:\Programming\url_shorter\backend\app\utils\make_link.py", line 5, in generate_code
    |     return ''.join(choices(string.ascii_letters + string.digits, k=length))
    |                    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\random.py", line 471, in choices
    |     return [population[floor(random() * n)] for i in _repeat(None, k)]
    |                                                      ~~~~~~~^^^^^^^^^
    | TypeError: 'range' object cannot be interpreted as an integer
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
                                   ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 18, in shorten
    code = generate_code()
  File "D:\Programming\url_shorter\backend\app\utils\make_link.py", line 5, in generate_code
    return ''.join(choices(string.ascii_letters + string.digits, k=length))
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\random.py", line 471, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
                                                     ~~~~~~~^^^^^^^^^
TypeError: 'range' object cannot be interpreted as an integer
[2025-06-06 12:03:37] uvicorn.error:55 WARNING - WatchFiles detected changes in 'utils\make_link.py'. Reloading...
[2025-06-06 12:03:37] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:03:37] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:03:37] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:03:37] uvicorn.error:93 INFO    - Finished server process [27896]
[2025-06-06 12:03:38] uvicorn.error:83 INFO    - Started server process [12112]
[2025-06-06 12:03:38] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:03:38] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - select pg_catalog.version()
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - select current_schema()
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - show standard_conforming_strings
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:1843 INFO    - [generated in 0.00037s] {'short_code_1': 'bZMfahbRciFHKGW'}
[2025-06-06 12:03:39] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:03:39] root:18 ERROR   - POST http://127.0.0.1:8000/shorten - ERROR - object bool can't be used in 'await' expression - 49.77ms
Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 19, in shorten
    if not await LinkRepositories.exists_code(code, db):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object bool can't be used in 'await' expression
[2025-06-06 12:03:39] uvicorn.error:414 ERROR   - Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 177, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     ) from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         self.scope, self.receive, self.send
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     )
    |     ^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    |     await self.simple_response(scope, receive, send, request_headers=headers)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    |     await self.app(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    |     with recv_stream, send_stream, collapse_excgroups():
    |                                    ~~~~~~~~~~~~~~~~~~^^
    |   File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    |     self.gen.throw(value)
    |     ~~~~~~~~~~~~~~^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    |     raise app_exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    |     await route.handle(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    |     raise exc
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     ...<3 lines>...
    |     )
    |     ^
    |   File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 19, in shorten
    |     if not await LinkRepositories.exists_code(code, db):
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: object bool can't be used in 'await' expression
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
                                   ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 19, in shorten
    if not await LinkRepositories.exists_code(code, db):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object bool can't be used in 'await' expression
[2025-06-06 12:03:51] uvicorn.error:55 WARNING - WatchFiles detected changes in 'api\v1\link_router.py'. Reloading...
[2025-06-06 12:03:51] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:03:51] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:03:51] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:03:51] uvicorn.error:93 INFO    - Finished server process [12112]
[2025-06-06 12:03:52] uvicorn.error:83 INFO    - Started server process [2364]
[2025-06-06 12:03:52] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:03:52] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:03:52] uvicorn.error:55 WARNING - WatchFiles detected changes in 'api\v1\link_router.py'. Reloading...
[2025-06-06 12:03:52] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:03:52] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:03:52] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:03:52] uvicorn.error:93 INFO    - Finished server process [2364]
[2025-06-06 12:03:53] uvicorn.error:83 INFO    - Started server process [23468]
[2025-06-06 12:03:53] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:03:53] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:03:54] uvicorn.error:55 WARNING - WatchFiles detected changes in 'api\v1\link_router.py'. Reloading...
[2025-06-06 12:03:54] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:03:54] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:03:54] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:03:54] uvicorn.error:93 INFO    - Finished server process [23468]
[2025-06-06 12:03:55] uvicorn.error:55 WARNING - WatchFiles detected changes in 'api\v1\link_router.py'. Reloading...
[2025-06-06 12:03:55] uvicorn.error:83 INFO    - Started server process [12092]
[2025-06-06 12:03:55] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:03:55] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:03:55] uvicorn.error:134 ERROR   - Traceback (most recent call last):
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 699, in lifespan
    await receive()
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\asyncio\queues.py", line 186, in get
    await getter
asyncio.exceptions.CancelledError

[2025-06-06 12:03:56] uvicorn.error:83 INFO    - Started server process [11092]
[2025-06-06 12:03:56] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:03:56] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:04:00] uvicorn.error:55 WARNING - WatchFiles detected changes in 'api\v1\link_router.py'. Reloading...
[2025-06-06 12:04:00] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:04:00] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:04:00] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:04:00] uvicorn.error:93 INFO    - Finished server process [11092]
[2025-06-06 12:04:01] uvicorn.error:83 INFO    - Started server process [7412]
[2025-06-06 12:04:01] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:04:01] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - select pg_catalog.version()
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - select current_schema()
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - show standard_conforming_strings
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - [generated in 0.00050s] {'short_code_1': 'wCzme92QdF9cuUw'}
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - INSERT INTO links (original_url, short_code) VALUES (%(original_url)s::VARCHAR, %(short_code)s::VARCHAR) RETURNING links.id, links.original_url, links.short_code
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:1843 INFO    - [generated in 0.00033s] {'original_url': AnyHttpUrl('https://www.youtube.com/'), 'short_code': 'wCzme92QdF9cuUw'}
[2025-06-06 12:04:12] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:04:12] root:18 ERROR   - POST http://127.0.0.1:8000/shorten - ERROR - (psycopg.ProgrammingError) cannot adapt type 'AnyHttpUrl' using placeholder '%s' (format: AUTO)
[SQL: INSERT INTO links (original_url, short_code) VALUES (%(original_url)s::VARCHAR, %(short_code)s::VARCHAR) RETURNING links.id, links.original_url, links.short_code]
[parameters: {'original_url': AnyHttpUrl('https://www.youtube.com/'), 'short_code': 'wCzme92QdF9cuUw'}]
(Background on this error at: https://sqlalche.me/e/20/f405) - 54.04ms
Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\psycopg\cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: cannot adapt type 'AnyHttpUrl' using placeholder '%s' (format: AUTO)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 22, in shorten
    link_obj = LinkRepositories.create(payload, code, db)
  File "D:\Programming\url_shorter\backend\app\repositories\link_repo.py", line 15, in create
    result =db.execute(stmt)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\orm\bulk_persistence.py", line 1294, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\psycopg\cursor.py", line 97, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.ProgrammingError: (psycopg.ProgrammingError) cannot adapt type 'AnyHttpUrl' using placeholder '%s' (format: AUTO)
[SQL: INSERT INTO links (original_url, short_code) VALUES (%(original_url)s::VARCHAR, %(short_code)s::VARCHAR) RETURNING links.id, links.original_url, links.short_code]
[parameters: {'original_url': AnyHttpUrl('https://www.youtube.com/'), 'short_code': 'wCzme92QdF9cuUw'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-06-06 12:04:12] uvicorn.error:414 ERROR   - Exception in ASGI application
Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\psycopg\cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.ProgrammingError: cannot adapt type 'AnyHttpUrl' using placeholder '%s' (format: AUTO)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
                                   ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\nicea\AppData\Local\Programs\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\middleware\log_middleware.py", line 15, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\url_shorter\backend\app\api\v1\link_router.py", line 22, in shorten
    link_obj = LinkRepositories.create(payload, code, db)
  File "D:\Programming\url_shorter\backend\app\repositories\link_repo.py", line 15, in create
    result =db.execute(stmt)
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\orm\bulk_persistence.py", line 1294, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Programming\url_shorter\.venv\Lib\site-packages\psycopg\cursor.py", line 97, in execute
    raise ex.with_traceback(None)
sqlalchemy.exc.ProgrammingError: (psycopg.ProgrammingError) cannot adapt type 'AnyHttpUrl' using placeholder '%s' (format: AUTO)
[SQL: INSERT INTO links (original_url, short_code) VALUES (%(original_url)s::VARCHAR, %(short_code)s::VARCHAR) RETURNING links.id, links.original_url, links.short_code]
[parameters: {'original_url': AnyHttpUrl('https://www.youtube.com/'), 'short_code': 'wCzme92QdF9cuUw'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-06-06 12:04:54] uvicorn.error:55 WARNING - WatchFiles detected changes in 'schemas\link_schemas.py'. Reloading...
[2025-06-06 12:04:54] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:04:54] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:04:54] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:04:54] uvicorn.error:93 INFO    - Finished server process [7412]
[2025-06-06 12:04:55] uvicorn.error:83 INFO    - Started server process [28420]
[2025-06-06 12:04:55] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:04:55] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:04:56] uvicorn.error:55 WARNING - WatchFiles detected changes in 'schemas\link_schemas.py'. Reloading...
[2025-06-06 12:04:56] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:04:56] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:04:56] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:04:56] uvicorn.error:93 INFO    - Finished server process [28420]
[2025-06-06 12:04:57] uvicorn.error:83 INFO    - Started server process [14224]
[2025-06-06 12:04:57] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:04:57] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:05:03] uvicorn.error:55 WARNING - WatchFiles detected changes in 'schemas\link_schemas.py'. Reloading...
[2025-06-06 12:05:03] uvicorn.error:263 INFO    - Shutting down
[2025-06-06 12:05:03] uvicorn.error:67 INFO    - Waiting for application shutdown.
[2025-06-06 12:05:03] uvicorn.error:76 INFO    - Application shutdown complete.
[2025-06-06 12:05:03] uvicorn.error:93 INFO    - Finished server process [14224]
[2025-06-06 12:05:06] uvicorn.error:55 WARNING - WatchFiles detected changes in 'schemas\link_schemas.py'. Reloading...
[2025-06-06 12:05:07] uvicorn.error:83 INFO    - Started server process [13896]
[2025-06-06 12:05:07] uvicorn.error:48 INFO    - Waiting for application startup.
[2025-06-06 12:05:07] uvicorn.error:62 INFO    - Application startup complete.
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - select pg_catalog.version()
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - select current_schema()
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - show standard_conforming_strings
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - [raw sql] {}
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - [generated in 0.00031s] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - INSERT INTO links (original_url, short_code) VALUES (%(original_url)s::VARCHAR, %(short_code)s::VARCHAR) RETURNING links.id, links.original_url, links.short_code
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:1843 INFO    - [generated in 0.00036s] {'original_url': 'https://www.youtube.com/', 'short_code': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:07] sqlalchemy.engine.Engine:2705 INFO    - COMMIT
[2025-06-06 12:05:07] root:25 INFO    - POST http://127.0.0.1:8000/shorten - 200 - 54.55ms
[2025-06-06 12:05:18] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:18] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:18] sqlalchemy.engine.Engine:1843 INFO    - [cached since 10.71s ago] {'short_code_1': 'all'}
[2025-06-06 12:05:18] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:18] root:25 INFO    - GET http://127.0.0.1:8000/all - 404 - 3.12ms
[2025-06-06 12:05:29] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:29] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:29] sqlalchemy.engine.Engine:1843 INFO    - [cached since 22.24s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:29] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:29] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.92ms
[2025-06-06 12:05:33] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:33] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:33] sqlalchemy.engine.Engine:1843 INFO    - [cached since 25.61s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:33] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:33] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.46ms
[2025-06-06 12:05:41] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:41] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:41] sqlalchemy.engine.Engine:1843 INFO    - [cached since 34.11s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:41] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:41] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.49ms
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - [cached since 34.75s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:42] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.52ms
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - [cached since 35.09s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:42] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.64ms
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - [cached since 35.33s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:42] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.53ms
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:1843 INFO    - [cached since 35.53s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:05:42] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:42] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.77ms
[2025-06-06 12:05:47] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:47] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:47] sqlalchemy.engine.Engine:1843 INFO    - [cached since 40.18s ago] {'short_code_1': 'ping'}
[2025-06-06 12:05:47] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:47] root:25 INFO    - GET http://127.0.0.1:8000/ping - 404 - 3.16ms
[2025-06-06 12:05:56] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:05:56] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:05:56] sqlalchemy.engine.Engine:1843 INFO    - [cached since 49.43s ago] {'short_code_1': 'ping'}
[2025-06-06 12:05:56] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:05:56] root:25 INFO    - GET http://127.0.0.1:8000/ping - 404 - 4.16ms
[2025-06-06 12:05:58] root:25 INFO    - GET http://127.0.0.1:8000/docs - 200 - 0.79ms
[2025-06-06 12:05:59] root:25 INFO    - GET http://127.0.0.1:8000/openapi.json - 200 - 2.56ms
[2025-06-06 12:06:04] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:06:04] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:06:04] sqlalchemy.engine.Engine:1843 INFO    - [cached since 56.93s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:06:04] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:06:04] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.89ms
[2025-06-06 12:06:58] sqlalchemy.engine.Engine:2699 INFO    - BEGIN (implicit)
[2025-06-06 12:06:58] sqlalchemy.engine.Engine:1843 INFO    - SELECT links.id, links.original_url, links.short_code 
FROM links 
WHERE links.short_code = %(short_code_1)s::VARCHAR
[2025-06-06 12:06:58] sqlalchemy.engine.Engine:1843 INFO    - [cached since 111.3s ago] {'short_code_1': '9GLOhhT6LHWLJW8'}
[2025-06-06 12:06:58] sqlalchemy.engine.Engine:2702 INFO    - ROLLBACK
[2025-06-06 12:06:58] root:25 INFO    - GET http://127.0.0.1:8000/9GLOhhT6LHWLJW8 - 307 - 2.51ms
